### ISSUE TITLE
IErrorReporter -> IcoLib

### ISSUE THREAD

**Issue by mhowlett** [jtippet/IcoTools#1]
Thanks, i'm using this! 

Propose moving `IErrorReporter` to IcoLib so you can remove the dependency on `IcoConsole` then package up IcoLib and put on nuget.org :-).

**Comment by jtippet** [comment]
Thanks.  That suggestion makes so much sense; the core library shouldn't depend on any console I/O frontend.  Fixed in 418b49806636c3b532c9a25e47d02e28add3265d.

Publishing to nuget makes sense too, but I'm still fairly inexperienced with the dotnet world, so I'll have to do some more learning before I'm comfortable committing to an API.  I suspect that some of the APIs in the current code are not done well.
